export const regions = [
  { id: 'valdora', name: 'Valdora, as Cinzas', tone: 'A aldeia queimada', level: 1, kind: 'cidade', unlock: null, people: 'refugiados e a curandeira Nara', foes: ['cão-de-cinza', 'saqueador do breu', 'mariposa de fuligem', 'vigia sem rosto'], resources: ['erva-lua', 'ferro velho'], event: 'Um sino toca sob as cinzas, embora a torre tenha desabado.', points: ['Casa de Eira', 'Torre do Sino', 'Poço selado'], secret: 'Sob o poço, uma passagem leva ao primeiro selo.' },
  { id: 'liria', name: 'Floresta de Liria', tone: 'Bosque de folhas prateadas', level: 2, kind: 'floresta', unlock: 'valdora', people: 'silvanos exilados e a batedora Maelis', foes: ['lobo de espinho', 'fada oca', 'corvo de vidro', 'raiz faminta'], resources: ['madeira-viva', 'erva-lua'], event: 'As árvores repetem em coro a última frase de quem passa.', points: ['Clareira do Veado', 'Árvore-Mãe', 'Ninho de Vidro'], secret: 'Uma raiz oca esconde um mapa para a cripta real.' },
  { id: 'nacre', name: 'Ruínas de Nacre', tone: 'Cidade afogada em pedra', level: 4, kind: 'ruínas', unlock: 'liria', people: 'arqueólogos e ecos dos antigos reis', foes: ['sentinela rachado', 'escriba espectral', 'escaravelho de bronze', 'cavaleiro de sal'], resources: ['prata antiga', 'pó de selo'], event: 'Inscrições mudam quando o grupo mente.', points: ['Arquivo Partido', 'Salão das Sete Portas', 'Cisterna'], secret: 'A porta sem maçaneta abre com o nome de Eira.' },
  { id: 'vhal', name: 'Montanhas de Vhal', tone: 'Picos sob auroras frias', level: 6, kind: 'montanha', unlock: 'nacre', people: 'clãs de mineiros e a ferreira Ysold', foes: ['cabrito de gelo', 'harpia de granizo', 'golem de ardósia', 'monge da geada'], resources: ['cristal-frio', 'minério de estrela'], event: 'Uma avalanche separa o grupo até alguém ceder seu equipamento.', points: ['Mina do Céu', 'Ponte dos Juramentos', 'Observatório'], secret: 'O observatório guarda a rota para o ermo.' },
  { id: 'sarga', name: 'Pântano de Sarga', tone: 'Brejo de luzes errantes', level: 8, kind: 'pântano', unlock: 'vhal', people: 'barqueiros, bruxas-das-marés e a boticária Oru', foes: ['afogado-cantor', 'sanguessuga-rúnica', 'bruxa do lodo', 'cervo putrefato'], resources: ['lótus-negro', 'seiva amarga'], event: 'Uma luz azul oferece um atalho e cobra uma lembrança.', points: ['Vila das Estacas', 'Jardim Submerso', 'Balsa dos Mortos'], secret: 'Um sino debaixo d’água silencia os mortos.' },
  { id: 'azrakh', name: 'Deserto de Azrakh', tone: 'Dunas de vidro negro', level: 10, kind: 'deserto', unlock: 'sarga', people: 'caravanas nômades e astrônomos exilados', foes: ['espectro de miragem', 'escorpião-âmbar', 'saqueador solar', 'serpente de vidro'], resources: ['âmbar solar', 'sal de sombra'], event: 'A noite cai ao meio-dia; cada viajante vê um futuro diferente.', points: ['Caravana de Nima', 'Farol Invertido', 'Mar de Vidro'], secret: 'A estrela caída contém uma memória de Nharos.' },
  { id: 'bastiao', name: 'Fortaleza de Kharad', tone: 'Muralhas rubras em guerra', level: 12, kind: 'fortaleza', unlock: 'azrakh', people: 'desertores, prisioneiros e a capitã Serik', foes: ['legionário eclipsado', 'canhoneiro de cinza', 'cão de guerra rúnico', 'cavaleiro do juramento'], resources: ['aço-rubro', 'pó de selo'], event: 'O comandante oferece rendição se um companheiro for entregue.', points: ['Portão Rubro', 'Quartel das Correntes', 'Sala do Estandarte'], secret: 'O túnel de drenagem chega ao trono sem cruzar as muralhas.' },
  { id: 'limiar', name: 'Limiar do Eclipse', tone: 'O fim onde o céu toca o abismo', level: 15, kind: 'região final', unlock: 'bastiao', people: 'os sobreviventes que restaram e vozes de todos os reinos', foes: ['fragmento faminto', 'anjo sem aurora', 'devorador de nomes', 'guardião do nada'], resources: ['luz-primordial', 'essência de Nharos'], event: 'O cenário assume a forma da lembrança que o protagonista mais teme.', points: ['Escadaria Impossível', 'Coração do Eclipse', 'Trono Vazio'], secret: 'Há um caminho de volta: alguém precisa lembrar o nome verdadeiro.' }
];

export const archetypes = {
  sentinel: { name: 'Sentinela', desc: 'Aço e proteção; lento, mas difícil de derrubar.', stats: { hp: 28, mp: 5, vigor: 11, atk: 8, mag: 2, def: 8, spd: 4 }, skills: ['shield-bash', 'guard'] },
  arcanist: { name: 'Arcanista', desc: 'Magia explosiva; frágil e dependente de mana.', stats: { hp: 17, mp: 15, vigor: 5, atk: 3, mag: 9, def: 3, spd: 6 }, skills: ['ember', 'frost-bind'] },
  ranger: { name: 'Batedor', desc: 'Precisão e iniciativa; sofre em confrontos longos.', stats: { hp: 21, mp: 7, vigor: 9, atk: 7, mag: 3, def: 4, spd: 9 }, skills: ['aimed-shot', 'poison-edge'] },
  warden: { name: 'Guardião', desc: 'Sustento e controle; danos moderados e versáteis.', stats: { hp: 23, mp: 11, vigor: 8, atk: 5, mag: 6, def: 6, spd: 5 }, skills: ['mend', 'thunder-mark'] }
};

export const specializations = {
  sentinel: [{ id: 'bulwark', name: 'Muralha viva', desc: 'Defesa +4 e guarda dura por um turno extra.' }, { id: 'vanguard', name: 'Vanguarda', desc: 'Ataque +3; primeiro golpe contra chefe causa +15% dano.' }],
  arcanist: [{ id: 'elementalist', name: 'Tecelão elemental', desc: 'Magia +4; fraquezas elementais causam +10% dano.' }, { id: 'umbra', name: 'Umbrólogo', desc: 'Mana máxima +6 e chance de reduzir dano recebido +12%.' }],
  ranger: [{ id: 'pathfinder', name: 'Batedor de trilha', desc: 'Velocidade +3 e esquiva +5%.' }, { id: 'deadeye', name: 'Olho morto', desc: 'Crítico +12% e precisão +5%.' }],
  warden: [{ id: 'healer', name: 'Mão de cura', desc: 'Cura recebida e lançada +25%; mana máxima +3.' }, { id: 'stormcaller', name: 'Chamador da tormenta', desc: 'Magia +3 e habilidades de raio causam +20% dano.' }]
};

export const skills = {
  'shield-bash': { name: 'Golpe de escudo', cost: 3, scale: 'atk', power: 1.25, element: 'physical', status: 'stun', chance: 0.2, target: 'enemy', desc: 'Dano físico e chance de atordoar.' },
  guard: { name: 'Postura firme', cost: 2, target: 'self', effect: 'guard', desc: 'Reduz pela metade o próximo dano recebido.' },
  ember: { name: 'Brasa errante', cost: 4, scale: 'mag', power: 1.55, element: 'fire', status: 'burn', chance: 0.35, target: 'enemy', desc: 'Fogo mágico; queima alvos.' },
  'frost-bind': { name: 'Grilhão de geada', cost: 5, scale: 'mag', power: 0.8, element: 'ice', status: 'freeze', chance: 0.3, target: 'enemy', desc: 'Dano de gelo; pode congelar.' },
  'aimed-shot': { name: 'Disparo certeiro', cost: 3, scale: 'atk', power: 1.45, element: 'physical', accuracy: 0.98, target: 'enemy', desc: 'Ataque físico de alta precisão.' },
  'poison-edge': { name: 'Lâmina tóxica', cost: 4, scale: 'atk', power: 0.9, element: 'poison', status: 'poison', chance: 0.65, target: 'enemy', desc: 'Ferida envenenada que persiste.' },
  mend: { name: 'Remendo vital', cost: 4, scale: 'mag', power: 1.7, target: 'ally', desc: 'Restaura vida de um aliado.' },
  'thunder-mark': { name: 'Marca do trovão', cost: 5, scale: 'mag', power: 1.2, element: 'lightning', status: 'stun', chance: 0.25, target: 'enemy', desc: 'Raio que pode interromper ações.' },
  'shadow-lance': { name: 'Lança umbral', cost: 6, scale: 'mag', power: 1.65, element: 'shadow', status: 'weaken', chance: 0.25, target: 'enemy', desc: 'Sombra que enfraquece o alvo.' },
  'battle-song': { name: 'Canto de marcha', cost: 5, target: 'party', effect: 'inspire', desc: 'Aumenta ataque do grupo por dois turnos.' },
  'sunder-armor': { name: 'Quebra-armadura', cost: 5, scale: 'atk', power: 1.1, element: 'physical', status: 'weaken', chance: 0.7, target: 'enemy', desc: 'Reduz a defesa do alvo.' },
  'first-light': { name: 'Primeira luz', cost: 8, scale: 'mag', power: 2.1, element: 'light', status: 'silence', chance: 0.3, target: 'enemy', desc: 'Rajada luminosa que pode silenciar.' }
};

export const companions = [
  { id: 'maelis', name: 'Maelis Venn', role: 'Batedora silvana', class: 'ranger', history: 'Abandonou a Árvore-Mãe para impedir o sacrifício dos refugiados de Valdora.', personality: 'Irônica, protetora e desconfiada de reis.', skill: 'aimed-shot', personalQuest: 'A raiz que não esquece', greeting: 'Se ouvir as árvores chamando pelo seu nome, não responda. Elas ainda não sabem quem você é.', stats: { hp: 24, atk: 8, mag: 3, def: 4, spd: 10 } },
  { id: 'oren', name: 'Oren Vask', role: 'Escriba e arcanista', class: 'arcanist', history: 'Copiou os selos de Nacre e esconde que seu mestre ajudou a quebrá-los.', personality: 'Meticuloso; prefere uma verdade dolorosa a uma esperança falsa.', skill: 'frost-bind', personalQuest: 'O nome apagado', greeting: 'As ruínas não estão em silêncio. Somos nós que desaprendemos a escutá-las.', stats: { hp: 19, atk: 3, mag: 10, def: 3, spd: 6 } },
  { id: 'ysold', name: 'Ysold Brasa-Fria', role: 'Ferreira sentinela', class: 'sentinel', history: 'Fechou as comportas da Mina do Céu com o irmão ainda do outro lado.', personality: 'Direta, leal e incapaz de perdoar promessas vagas.', skill: 'shield-bash', personalQuest: 'O peso do ferro', greeting: 'Não prometo que vai ficar bonito. Prometo que não vai quebrar.', stats: { hp: 31, atk: 8, mag: 2, def: 9, spd: 4 } },
  { id: 'oru', name: 'Oru das Estacas', role: 'Boticária do brejo', class: 'warden', history: 'Carrega a praga que salvou sua vila e procura a cura sem apagar os mortos.', personality: 'Gentil e feroz quando alguém chama doentes de monstros.', skill: 'mend', personalQuest: 'O remédio e o veneno', greeting: 'Sente-se. Se vai morrer, ao menos não faça isso em pé no meu consultório.', stats: { hp: 25, atk: 5, mag: 8, def: 6, spd: 6 } },
  { id: 'nima', name: 'Nima al-Sahir', role: 'Astrônoma errante', class: 'arcanist', history: 'Descobriu que as estrelas estão sendo devoradas uma a uma.', personality: 'Curiosa, impaciente e generosa com quem admite não saber.', skill: 'thunder-mark', personalQuest: 'Uma estrela para voltar', greeting: 'O céu não é vazio. É só muito grande para caber numa única certeza.', stats: { hp: 20, atk: 4, mag: 9, def: 4, spd: 7 } },
  { id: 'serik', name: 'Capitã Serik', role: 'Desertora de Kharad', class: 'sentinel', history: 'Desertou quando recebeu ordens para usar refugiados como escudo.', personality: 'Disciplinada; não confunde obediência com honra.', skill: 'sunder-armor', personalQuest: 'A bandeira que queimou', greeting: 'Não me chame de heroína. Eu só parei de obedecer tarde demais.', stats: { hp: 29, atk: 8, mag: 3, def: 8, spd: 5 } }
];

const seeds = [
  ['Cão-de-cinza','valdora',12,4,1,'fire','ice','physical','Investida'],['Saqueador do breu','valdora',15,5,2,'shadow','light','physical','Golpe baixo'],['Mariposa de fuligem','valdora',10,3,1,'ice','fire','shadow','Pó cego'],['Vigia sem rosto','valdora',20,6,4,'physical','lightning','shadow','Olhar vazio'],
  ['Lobo de espinho','liria',24,7,3,'physical','fire','poison','Matilha'],['Fada oca','liria',18,4,2,'fire','ice','shadow','Véu de pólen'],['Corvo de vidro','liria',21,6,2,'lightning','physical','ice','Mergulho'],['Raiz faminta','liria',30,8,5,'ice','fire','poison','Enredar'],
  ['Sentinela rachado','nacre',37,9,8,'lightning','physical','ice','Protocolo de guarda'],['Escriba espectral','nacre',29,7,4,'light','shadow','ice','Apagar nome'],['Escaravelho de bronze','nacre',35,8,9,'physical','lightning','fire','Casco'],['Cavaleiro de sal','nacre',43,10,8,'ice','fire','physical','Lança de sal'],
  ['Cabrito de gelo','vhal',48,11,8,'fire','ice','physical','Chifrada'],['Harpia de granizo','vhal',40,12,5,'lightning','ice','physical','Rajada'],['Golem de ardósia','vhal',65,12,13,'physical','lightning','ice','Punho sísmico'],['Monge da geada','vhal',52,11,8,'fire','ice','shadow','Círculo frio'],
  ['Afogado-cantor','sarga',62,13,8,'light','poison','ice','Canto submerso'],['Sanguessuga-rúnica','sarga',45,10,6,'fire','poison','shadow','Dreno'],['Bruxa do lodo','sarga',56,14,7,'lightning','poison','ice','Poção turva'],['Cervo putrefato','sarga',70,14,9,'fire','poison','physical','Galhada podre'],
  ['Espectro de miragem','azrakh',77,16,10,'light','shadow','fire','Dobra de calor'],['Escorpião-âmbar','azrakh',72,17,12,'ice','fire','poison','Ferrão solar'],['Saqueador solar','azrakh',68,17,8,'ice','fire','physical','Lâmina cega'],['Serpente de vidro','azrakh',84,18,11,'ice','fire','lightning','Espiral cortante'],
  ['Legionário eclipsado','bastiao',98,19,16,'light','shadow','fire','Muralha humana'],['Canhoneiro de cinza','bastiao',78,22,8,'lightning','fire','ice','Disparo carregado'],['Cão de guerra rúnico','bastiao',90,20,12,'ice','shadow','physical','Marca de caça'],['Cavaleiro do juramento','bastiao',110,21,18,'lightning','physical','fire','Desafio'],
  ['Fragmento faminto','limiar',125,24,18,'light','shadow','physical','Mordida do vazio'],['Anjo sem aurora','limiar',118,25,15,'shadow','light','ice','Lança celeste'],['Devorador de nomes','limiar',140,23,17,'light','shadow','poison','Roubar memória'],['Guardião do nada','limiar',160,27,22,'light','shadow','lightning','Silêncio absoluto']
];
export const enemies = seeds.map(([name, region, hp, atk, def, weakness, resist, element, move], index) => ({ id: `foe-${index + 1}`, name, region, level: Math.max(1, regions.findIndex(item => item.id === region) * 2 + 1), hp, atk, def, weakness, resist, element, move, xp: 12 + index * 3, gold: 5 + index * 2, drop: index % 2 ? 'erva-lua' : 'ferro velho', ai: ['aggressive','tactical','trickster'][index % 3] }));

export const bosses = [
  { id: 'bell-warden', name: 'O Vigia do Sino', region: 'valdora', hp: 76, atk: 8, def: 5, weakness: 'light', resist: 'shadow', phases: ['Ataca quem tiver menos vida.', 'Abaixo de 35% PV, cinzas ferem todo o grupo.'], reward: 'Sino de Eira', story: 'Dain, irmão de Eira, acorrentou-se à torre para conter o fragmento. As cinzas o mantêm vivo há trezentos anos.', move: 'Badalada fúnebre' },
  { id: 'root-mother', name: 'A Mãe sob as Raízes', region: 'liria', hp: 170, atk: 14, def: 9, weakness: 'fire', resist: 'poison', phases: ['Enraíza o aliado mais rápido.', 'Aos 50%, floresce esporos; fogo interrompe a floração.'], reward: 'Semente da Árvore-Mãe', story: 'A guardiã alimentou o selo com memórias silvanas. Maelis pode convencê-la a parar oferecendo uma memória sua.', move: 'Abraço das raízes' },
  { id: 'king-nacre', name: 'Rei Odran, o Sem Nome', region: 'nacre', hp: 250, atk: 18, def: 14, weakness: 'lightning', resist: 'ice', phases: ['Copia a última habilidade do grupo.', 'Apaga uma habilidade; quebrar inscrições restaura-a.'], reward: 'Coroa de Nacre', story: 'Odran apagou o próprio nome para esconder que ordenou o sacrifício dos outros seis reinos.', move: 'Decreto apagado' },
  { id: 'sky-eater', name: 'A Boca da Montanha', region: 'vhal', hp: 330, atk: 23, def: 20, weakness: 'fire', resist: 'ice', phases: ['Armadura reduz dano em 40%; atacar a forja a desativa.', 'Abalo sísmico: defender evita a queda.'], reward: 'Martelo do Céu', story: 'Um verme estelar despertou na mina quando Ysold fechou as comportas que mataram seu irmão.', move: 'Queda de ardósia' },
  { id: 'drowned-saint', name: 'Santa das Águas Mortas', region: 'sarga', hp: 410, atk: 28, def: 22, weakness: 'lightning', resist: 'poison', phases: ['Invoca ecos enquanto a água sobe.', 'O sino submerso remove regeneração por três turnos.'], reward: 'Lótus da Última Maré', story: 'Oru reconhece a santa como a mãe que os moradores afogaram para deter a praga.', move: 'Maré de luto' },
  { id: 'glass-oracle', name: 'O Oráculo de Vidro', region: 'azrakh', hp: 520, atk: 31, def: 24, weakness: 'ice', resist: 'fire', phases: ['Cria miragens; atingir a sombra verdadeira dissipa-as.', 'Prevê ações repetidas e as rebate.'], reward: 'Astrolábio Solar', story: 'O oráculo é um futuro de Nima que sacrificou as caravanas para salvar o céu.', move: 'Futuro partido' },
  { id: 'red-commander', name: 'Marechal Veyr, Mão de Kharad', region: 'bastiao', hp: 690, atk: 35, def: 29, weakness: 'poison', resist: 'physical', phases: ['Canhoneiros recebem ordens; silenciar Veyr as cancela.', 'Aos 40%, desafia o protagonista e quebra a guarda.'], reward: 'Estandarte sem Rei', story: 'Veyr prolongou a guerra para dividir os reinos. Serik pode julgá-lo ou aceitar sua rendição.', move: 'Ordem de execução' },
  { id: 'nharos', name: 'Nharos, Aquilo que Apaga', region: 'limiar', hp: 980, atk: 42, def: 32, weakness: 'light', resist: 'shadow', phases: ['Copia o último elemento e resiste a ele.', 'Aos 65%, separa o grupo em lembranças; aliados rompem os laços.', 'Aos 25%, oferece devolver Valdora em troca de um nome amado.'], reward: 'Coração do Eclipse', story: 'Nharos é o intervalo entre os sóis, alimentado por trezentos anos de pactos. Não quer governar: quer que nada tenha sido perdido.', move: 'Silêncio do mundo' }
];

export const equipment = [
  ['Espada do Vigia','weapon','physical','common',3,0,1],['Machado de lenhador','weapon','physical','common',5,0,-1],['Lança de junco','weapon','physical','uncommon',4,0,2],['Adaga de Valdora','weapon','physical','uncommon',3,0,3],['Arco de teixo','weapon','physical','uncommon',4,0,2],['Cajado de salgueiro','weapon','magic','uncommon',0,4,1],['Grimório das marés','weapon','magic','rare',0,6,0],['Escudo da torre','offhand','defense','common',0,0,4],['Broquel de vidro','offhand','defense','rare',1,0,3],['Couraça de couro','armor','defense','common',0,0,4],
  ['Elmo de batedor','helmet','defense','common',0,0,2],['Botas de trilha','boots','speed','uncommon',0,0,1],['Luvas de ferreiro','gloves','physical','uncommon',2,0,1],['Anel de cobre vivo','accessory','health','common',0,0,0],['Amuleto de cinza','accessory','magic','uncommon',0,2,0],['Faca de osso lunar','weapon','physical','rare',5,0,3],['Lança da clareira','weapon','physical','rare',7,0,2],['Arco de vidro verde','weapon','physical','rare',6,0,3],['Machado de ardósia','weapon','physical','rare',9,0,-1],['Espada de Nacre','weapon','physical','epic',10,0,2],
  ['Cajado do céu oco','weapon','magic','epic',0,12,1],['Grimório sem nome','weapon','magic','epic',1,11,0],['Adagas da balsa','weapon','physical','epic',8,0,5],['Escudo da comporta','offhand','defense','rare',0,0,9],['Manto de Oru','armor','defense','rare',0,3,6],['Elmo de gelo azul','helmet','defense','rare',0,1,6],['Botas do sal','boots','speed','rare',0,0,2],['Luvas do trovão','gloves','magic','epic',1,4,2],['Anel de âmbar solar','accessory','health','rare',0,1,0],['Colar de lótus-negro','accessory','magic','rare',0,4,1],
  ['Lâmina do eclipse','weapon','physical','legendary',15,4,3],['Machado do verme estelar','weapon','physical','legendary',19,0,-2],['Lança das sete portas','weapon','physical','legendary',14,3,5],['Arco da estrela caída','weapon','physical','legendary',13,5,6],['Cajado da primeira luz','weapon','magic','legendary',2,17,2],['Grimório de Nharos','weapon','magic','mythic',4,21,1],['Escudo do último reino','offhand','defense','legendary',0,2,15],['Armadura de placas rubras','armor','defense','epic',1,0,12],['Couraça de escamas de vidro','armor','defense','legendary',2,3,10],['Manto da aurora extinta','armor','defense','mythic',2,8,9],
  ['Elmo do marechal','helmet','defense','epic',2,0,9],['Elmo sem aurora','helmet','magic','legendary',0,5,7],['Botas de vento astral','boots','speed','epic',0,1,1],['Botas do Limiar','boots','speed','legendary',1,0,3],['Luvas da forja celeste','gloves','physical','legendary',7,0,4],['Luvas do tecelão','gloves','magic','rare',0,3,2],['Anel das duas luas','accessory','health','epic',2,2,0],['Anel do nome verdadeiro','accessory','magic','legendary',0,8,2],['Amuleto de Eira','accessory','health','mythic',4,5,3],['Broche da caravaneira','accessory','speed','uncommon',0,1,1],['Égide da Árvore-Mãe','offhand','defense','mythic',2,4,18],['Espada da aurora partida','weapon','physical','mythic',18,10,4],['Lança do juramento','weapon','physical','epic',12,0,8],['Cajado de cristal-frio','weapon','magic','rare',0,9,2],['Arco das raízes','weapon','physical','uncommon',5,1,4]
].map(([name, slot, kind, rarity, atk, mag, def], index) => ({ id: `gear-${index + 1}`, name, slot, kind, rarity, atk, mag, def, spd: kind === 'speed' ? Math.max(1, Math.ceil((atk + mag + def) / 3)) : 0, hp: kind === 'health' ? 6 + Math.floor(index / 12) * 2 : 0, mp: kind === 'magic' ? Math.max(1, Math.floor(mag / 5)) : 0, level: index < 15 ? 1 : Math.max(1, Math.floor((index - 12) / 4) + 1), effect: index % 7 === 0 ? 'Crítico +5%' : index % 7 === 3 ? 'Resistência elemental +8%' : index % 9 === 0 ? 'Dreno de vida +3%' : null, price: (index + 1) * 12 }));

export const items = {
  'erva-lua': { id: 'erva-lua', name: 'Erva-lua', kind: 'material', desc: 'Folha prateada usada em tônicos.', price: 3 }, 'ferro velho': { id: 'ferro velho', name: 'Ferro velho', kind: 'material', desc: 'Metal recuperável para forja.', price: 4 }, 'madeira-viva': { id: 'madeira-viva', name: 'Madeira-viva', kind: 'material', desc: 'Madeira que retém o calor da floresta.', price: 6 }, 'prata antiga': { id: 'prata antiga', name: 'Prata antiga', kind: 'material', desc: 'Prata gravada com a língua dos reis.', price: 10 }, 'pó de selo': { id: 'pó de selo', name: 'Pó de selo', kind: 'material', desc: 'Resíduo dos antigos pactos.', price: 14 }, 'cristal-frio': { id: 'cristal-frio', name: 'Cristal-frio', kind: 'material', desc: 'Núcleo que não derrete.', price: 12 }, 'minério de estrela': { id: 'minério de estrela', name: 'Minério de estrela', kind: 'material', desc: 'Fragmento celeste de forja avançada.', price: 20 }, 'lótus-negro': { id: 'lótus-negro', name: 'Lótus-negro', kind: 'material', desc: 'Flor que cresce onde alguém foi esquecido.', price: 14 }, 'seiva amarga': { id: 'seiva amarga', name: 'Seiva amarga', kind: 'material', desc: 'Neutraliza toxinas em mistura cuidadosa.', price: 9 }, 'âmbar solar': { id: 'âmbar solar', name: 'Âmbar solar', kind: 'material', desc: 'Luz antiga presa em resina.', price: 18 }, 'sal de sombra': { id: 'sal de sombra', name: 'Sal de sombra', kind: 'material', desc: 'Proteção contra o vazio.', price: 17 }, 'aço-rubro': { id: 'aço-rubro', name: 'Aço-rubro', kind: 'material', desc: 'Aço das forjas de Kharad.', price: 22 }, 'luz-primordial': { id: 'luz-primordial', name: 'Luz primordial', kind: 'material', desc: 'Uma fagulha anterior ao eclipse.', price: 50 },
  'poção vital': { id: 'poção vital', name: 'Poção vital', kind: 'consumable', desc: 'Restaura 35 PV.', price: 18, effect: 'heal', amount: 35 }, 'tônico de éter': { id: 'tônico de éter', name: 'Tônico de éter', kind: 'consumable', desc: 'Restaura 12 PM.', price: 20, effect: 'mana', amount: 12 }, 'antídoto': { id: 'antídoto', name: 'Antídoto', kind: 'consumable', desc: 'Remove veneno e queimadura.', price: 11, effect: 'cure', amount: 0 }, 'bomba de fuligem': { id: 'bomba de fuligem', name: 'Bomba de fuligem', kind: 'consumable', desc: 'Causa 22 de dano de fogo.', price: 24, effect: 'bomb', amount: 22 }
};

export const recipes = [
  { id: 'recipe-tonic', name: 'Tônico de éter', needs: { 'erva-lua': 2, 'seiva amarga': 1 }, makes: 'tônico de éter', count: 1 }, { id: 'recipe-potion', name: 'Poção vital', needs: { 'erva-lua': 2, 'lótus-negro': 1 }, makes: 'poção vital', count: 1 }, { id: 'recipe-bomb', name: 'Bomba de fuligem', needs: { 'ferro velho': 1, 'pó de selo': 1 }, makes: 'bomba de fuligem', count: 1 }, { id: 'recipe-upgrade', name: 'Aprimorar equipamento', needs: { 'minério de estrela': 1, 'aço-rubro': 1 }, upgrade: true }
];

export const sideQuests = [
  ['Cinzas na soleira','valdora','Encontre a lista de refugiados na Casa de Eira.','poção vital',25],['O sino sob o poço','valdora','Investigue o eco e escolha quem segura a corda.','Sino de Eira',35],['Duas tigelas','valdora','Recolha 2 ervas-lua e divida o remédio com os feridos.','erva-lua',22],['A caça que voltou','liria','Derrote 2 lobos de espinho perto da clareira.','madeira-viva',45],['Sementes emprestadas','liria','Entregue madeira-viva à Árvore-Mãe.','poção vital',40],['Ninho de vidro','liria','Recupere um ovo de cristal e decida seu destino.','Broquel de vidro',52],['O livro molhado','nacre','Traga uma página ao Arquivo Partido.','prata antiga',65],['Sete portas, uma mentira','nacre','Descubra qual inscrição foi alterada.','pó de selo',70],['O último nome','nacre','Devolva um nome apagado ao túmulo real.','Coroa de Nacre',75],['Minério no escuro','vhal','Extraia 2 cristais sem acordar o golem.','cristal-frio',90],['A ponte dos juramentos','vhal','Reconcilie os clãs antes que a ponte caia.','minério de estrela',95],['Uma carta congelada','vhal','Encontre a carta do irmão de Ysold.','aço-rubro',100],['Balsa dos mortos','sarga','Leve Oru à outra margem sem abandonar doentes.','lótus-negro',110],['A febre azul','sarga','Crie o antídoto e decida quem recebe a dose.','seiva amarga',115],['Sino sem água','sarga','Silencie o sino submerso.','Lótus da Última Maré',120],['Caravana de Nima','azrakh','Proteja a caravana ou negocie passagem segura.','âmbar solar',135],['Uma sombra no mapa','azrakh','Localize a estrela caída no Mar de Vidro.','sal de sombra',140],['Três futuros','azrakh','Escolha qual visão do farol será preservada.','Astrolábio Solar',145],['O desertor do portão','bastiao','Ajude um soldado a sair sem delatar prisioneiros.','aço-rubro',160],['Bandeira queimada','bastiao','Recupere o estandarte para um julgamento público.','Estandarte sem Rei',170]
].map(([name, region, objective, reward, gold], index) => ({ id: `side-${index + 1}`, name, region, objective, reward, gold, state: 'available', choice: index % 3 === 2 }));

export const chapters = [
  { id: 'prologue', title: 'Prólogo: A última manhã', region: 'valdora', objective: 'Escape das cinzas e vença o Vigia do Sino.', scenes: [
    { speaker: 'Eira', text: 'O sol sumiu antes do café. A sombra veio depois. Se a casa cair, corre para o poço; eu vou atrás.', choices: [{ text: 'Voltar por Dain, preso na torre.', key: 'savedDain', value: true, consequence: 'Dain vive e o sino fica quieto.' }, { text: 'Levar Eira e os feridos ao poço.', key: 'savedRefugees', value: true, consequence: 'Refugiados sobrevivem; Dain fica para trás.' }] },
    { speaker: 'Maelis', text: 'Essa luz na sua mão não é fogo. É um fragmento. Se os homens de Veyr virem, chamarão você de arma.', choices: [{ text: 'Confiar a verdade a Maelis.', key: 'trustedMaelis', value: true, consequence: 'Maelis começa com afinidade +2.' }, { text: 'Esconder a marca até Nacre.', key: 'hidMark', value: true, consequence: 'Oren não desconfiará de você.' }] },
    { speaker: 'Vigia do Sino', text: 'TREZENTOS INVERNOS. DAIN PROMETEU QUE O SOL VOLTARIA.', choices: [{ text: '“A promessa acabou. Eu não.”', key: 'defiedWarden', value: true, consequence: 'O primeiro selo reconhece sua vontade.' }, { text: 'Responder com o nome de Eira.', key: 'sparedWarden', value: true, consequence: 'O Vigia hesita; Eira recordará o gesto.' }] }
  ] },
  { id: 'chapter-1', title: 'Capítulo I: A floresta que escuta', region: 'liria', objective: 'Descubra por que a Árvore-Mãe devora lembranças.', scenes: [{ speaker: 'Maelis', text: 'Minha mãe não lembra mais meu rosto. A árvore chama isso de preço justo. Eu chamo de fome.', choices: [{ text: 'Oferecer uma lembrança sua.', key: 'gaveMemory', value: true, consequence: 'Maelis ganha afinidade; perde-se um diálogo sobre Eira.' }, { text: 'Procurar alternativa nas raízes antigas.', key: 'soughtRootWay', value: true, consequence: 'Abre um segredo e uma batalha mais difícil.' }] }] },
  { id: 'chapter-2', title: 'Capítulo II: O rei sem nome', region: 'nacre', objective: 'Derrote Odran e leia a confissão no Arquivo Partido.', scenes: [{ speaker: 'Oren', text: 'Eu copiei o selo. Meu mestre pediu uma cópia, não uma chave. Odran usou as duas.', choices: [{ text: 'Exigir que Oren conte a verdade.', key: 'exposedOren', value: true, consequence: 'Nacre confia no grupo; Oren entra debilitado.' }, { text: 'Guardar a confissão até deter o rei.', key: 'protectedOren', value: true, consequence: 'Oren ganha afinidade; arquivos ficam fechados.' }] }] },
  { id: 'chapter-3', title: 'Capítulo III: A montanha partida', region: 'vhal', objective: 'Pare a Boca da Montanha e responda por Ysold.', scenes: [{ speaker: 'Ysold', text: 'Meu irmão fechou a forja por dentro. Eu disse que voltava. Trouxe ferramentas, não coragem.', choices: [{ text: 'Dizer que a culpa não foi dela.', key: 'comfortedYsold', value: true, consequence: 'Ysold entrega o martelo do irmão.' }, { text: 'Prometer encontrar os restos dele.', key: 'searchedBrother', value: true, consequence: 'Abre a câmara e uma arma lendária.' }] }] },
  { id: 'chapter-4', title: 'Capítulo IV: A santa submersa', region: 'sarga', objective: 'Silencie o sino ou convença a santa a descansar.', scenes: [{ speaker: 'Oru', text: 'Minha mãe não virou um monstro quando adoeceu. Virou mãe. Ainda assim, fomos nós que a empurramos para o fundo.', choices: [{ text: 'Tocar o sino e soltar os mortos.', key: 'rangSargaBell', value: true, consequence: 'Oru ganha afinidade; cura exige materiais.' }, { text: 'Pedir que Oru tente uma cura.', key: 'curedSarga', value: true, consequence: 'A vila sobrevive, Oru carrega a doença.' }] }] },
  { id: 'chapter-5', title: 'Capítulo V: Um céu emprestado', region: 'azrakh', objective: 'Derrote o Oráculo e escolha que futuro será lembrado.', scenes: [{ speaker: 'Nima', text: 'Meu reflexo diz que uma vida é um preço pequeno por um mundo. O problema é que sempre escolhe a vida de outra pessoa.', choices: [{ text: 'Salvar as caravanas; deixar o farol apagar.', key: 'savedCaravans', value: true, consequence: 'Nima ganha afinidade; menos luz no final.' }, { text: 'Preservar o farol para fortalecer o grupo.', key: 'savedLighthouse', value: true, consequence: 'Mais poder no final; caravana perde a rota.' }] }] },
  { id: 'chapter-6', title: 'Capítulo VI: A bandeira de Kharad', region: 'bastiao', objective: 'Julgue Veyr e abra os portões sem sacrificar prisioneiros.', scenes: [{ speaker: 'Serik', text: 'Veyr diz que cada ordem salvou mil pessoas. Ele não conta os nomes dos que mandou para a muralha.', choices: [{ text: 'Entregar Veyr a julgamento aberto.', key: 'judgedVeyr', value: true, consequence: 'Serik permanece; Kharad oferece reforços.' }, { text: 'Aceitar sua rendição contra Nharos.', key: 'sparedVeyr', value: true, consequence: 'Veyr luta no final; Serik pode partir.' }] }] },
  { id: 'chapter-7', title: 'Capítulo VII: O intervalo entre sóis', region: 'limiar', objective: 'Enfrente Nharos e decida o destino dos sete fragmentos.', scenes: [{ speaker: 'Nharos', text: 'Eu não sou a noite. Sou o lugar vazio onde guardam os nomes de quem perderam. Deixe-me apagar a perda.', choices: [{ text: 'Unir os fragmentos e criar um novo sol.', key: 'endingDawn', value: true, consequence: 'Aurora: nasce um sol; o protagonista vira guardião.' }, { text: 'Selar Nharos e manter o crepúsculo.', key: 'endingDusk', value: true, consequence: 'Crepúsculo: os reinos sobrevivem sem promessa de luz.' }, { text: 'Aceitar o vazio e devolver Valdora.', key: 'endingVoid', value: true, consequence: 'Retorno: Valdora volta; protagonista e aliado são apagados.' }] }] }
];

export const statusDescriptions = { burn: 'queimadura: perde 5% PV máximo', poison: 'veneno: perde 7% PV máximo', bleed: 'sangramento: perde 4 PV', freeze: 'congelamento: perde um turno', stun: 'atordoamento: perde um turno', silence: 'silêncio: não pode usar habilidades', weaken: 'enfraquecido: ataque reduzido' };